### PR TITLE
boa-wow-pocem-gj

### PR DESCRIPTION
**Pull request by MennoCoehoorn**
Added 4 new cards

### CODE REVIEW

**Comment by slatinsky** [comment]
Please rename your images - extension has to be ```.png```:
```images/boa.PNG``` -> ```images/boa.png```
```images/gj.PNG``` -> ```images/gj.png```
```images/pocem.PNG``` -> ```images/pocem.png```
```images/wow.PNG``` -> ```images/wow.png```

**Comment by vikiival** [comment]
Pls remove wow.PNG 


There is wow.png already

**Comment by vikiival** [comment]
@Hladikes wdyt?

**Comment by Hladikes** [comment]
Looks good to me
image

**Review by vikiival — APPROVED** [review]

**Pull request merged**
