### PR TITLE
🧼 code cleanup

### LINKED ISSUE #13: Cleanup the code
- [ ] Move css to separate file
- [ ] Move vue/js to separate file
- [ ] set redirection rules correctly

### PR DESCRIPTION
**Pull request by Hladikes**
I divided index.html into a separate files. I also had to change redirect rules in order to resolve `style.css` and `app.js`

### CODE REVIEW

**Comment by vikiival** [comment]
Good, but I would not move it to /web

**Comment by Hladikes** [comment]
Ok, and where would you put it then ?

**Comment by vikiival** [comment]
I would keep it in the root folder

**Comment by Hladikes** [comment]
Are you sure ? To my eye, it looks quite difficult to navigate between files related to web, since they are mixed together with other readme and config files
image

**Comment by vikiival** [comment]
Tru ;D
Let's resolve conflict and merge this

**Comment by Hladikes** [comment]
👌 ❤️

**Pull request merged**
